package model;
// Generated 2 mars 2015 20:31:41 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name="category"
    ,catalog="stockmanager"
)
public class Category extends Metier implements java.io.Serializable {


     private Long idCategory;
     private String nameCategory;
     private String descriptionCategory;
     private Set products = new HashSet(0);

    public Category() {
    }

    public Category(String nameCategory, String descriptionCategory, Set products) {
       this.nameCategory = nameCategory;
       this.descriptionCategory = descriptionCategory;
       this.products = products;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdCategory", unique=true, nullable=false)
    public Long getIdCategory() {
        return this.idCategory;
    }
    
    public void setIdCategory(Long idCategory) {
        this.idCategory = idCategory;
    }

    
    @Column(name="NameCategory", length=65535)
    public String getNameCategory() {
        return this.nameCategory;
    }
    
    public void setNameCategory(String nameCategory) {
        this.nameCategory = nameCategory;
    }

    
    @Column(name="DescriptionCategory", length=65535)
    public String getDescriptionCategory() {
        return this.descriptionCategory;
    }
    
    public void setDescriptionCategory(String descriptionCategory) {
        this.descriptionCategory = descriptionCategory;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="category")
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


