package model;
// Generated 3 mars 2015 14:34:36 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name="category"
    ,catalog="stockmanager"
)
public class Category extends Metier implements java.io.Serializable {


     private long idCategory;
     private String nameCategory;
     private String descriptionCategory;
     private Set<Product> products = new HashSet(0);

    public Category() {
    }

	
    public Category(long idCategory) {
        this.idCategory = idCategory;
    }
    public Category(long idCategory, String nameCategory, String descriptionCategory, Set<Product> products) {
       this.idCategory = idCategory;
       this.nameCategory = nameCategory;
       this.descriptionCategory = descriptionCategory;
       this.products = products;
    }
   
     @Id 

    
    @Column(name="IdCategory", unique=true, nullable=false)
    public long getIdCategory() {
        return this.idCategory;
    }
    
    public void setIdCategory(long idCategory) {
        this.idCategory = idCategory;
    }

    
    @Column(name="NameCategory", length=65535)
    public String getNameCategory() {
        return this.nameCategory;
    }
    
    public void setNameCategory(String nameCategory) {
        this.nameCategory = nameCategory;
    }

    
    @Column(name="DescriptionCategory", length=65535)
    public String getDescriptionCategory() {
        return this.descriptionCategory;
    }
    
    public void setDescriptionCategory(String descriptionCategory) {
        this.descriptionCategory = descriptionCategory;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="category")
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


