package model;
// Generated 3 mars 2015 09:18:13 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name="customer"
    ,catalog="stockmanager"
)
public class Customer extends Metier implements java.io.Serializable {


     private Long idCustomer;
     private Long nameCustomer;
     private String siretCustomer;
     private String typeCustomer;
     private String adressCustomer;
     private String villeCustomer;
     private Long cpcustomer;
     private Set orderses = new HashSet(0);

    public Customer() {
    }

    public Customer(Long nameCustomer, String siretCustomer, String typeCustomer, String adressCustomer, String villeCustomer, Long cpcustomer, Set orderses) {
       this.nameCustomer = nameCustomer;
       this.siretCustomer = siretCustomer;
       this.typeCustomer = typeCustomer;
       this.adressCustomer = adressCustomer;
       this.villeCustomer = villeCustomer;
       this.cpcustomer = cpcustomer;
       this.orderses = orderses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdCustomer", unique=true, nullable=false)
    public Long getIdCustomer() {
        return this.idCustomer;
    }
    
    public void setIdCustomer(Long idCustomer) {
        this.idCustomer = idCustomer;
    }

    
    @Column(name="NameCustomer")
    public Long getNameCustomer() {
        return this.nameCustomer;
    }
    
    public void setNameCustomer(Long nameCustomer) {
        this.nameCustomer = nameCustomer;
    }

    
    @Column(name="SiretCustomer", length=65535)
    public String getSiretCustomer() {
        return this.siretCustomer;
    }
    
    public void setSiretCustomer(String siretCustomer) {
        this.siretCustomer = siretCustomer;
    }

    
    @Column(name="TypeCustomer", length=65535)
    public String getTypeCustomer() {
        return this.typeCustomer;
    }
    
    public void setTypeCustomer(String typeCustomer) {
        this.typeCustomer = typeCustomer;
    }

    
    @Column(name="AdressCustomer", length=65535)
    public String getAdressCustomer() {
        return this.adressCustomer;
    }
    
    public void setAdressCustomer(String adressCustomer) {
        this.adressCustomer = adressCustomer;
    }

    
    @Column(name="VilleCustomer", length=65535)
    public String getVilleCustomer() {
        return this.villeCustomer;
    }
    
    public void setVilleCustomer(String villeCustomer) {
        this.villeCustomer = villeCustomer;
    }

    
    @Column(name="CPCustomer")
    public Long getCpcustomer() {
        return this.cpcustomer;
    }
    
    public void setCpcustomer(Long cpcustomer) {
        this.cpcustomer = cpcustomer;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="customer")
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }




}


