package model;
// Generated 3 mars 2015 09:18:13 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name="employee"
    ,catalog="stockmanager"
)
public class Employee extends Metier implements java.io.Serializable {


     private Long idEmployee;
     private String nameEmployee;
     private String firstNameEmployee;
     private String emailEmployee;
     private String mdpEmployee;
     private Set orderses = new HashSet(0);

    public Employee() {
    }

    public Employee(String nameEmployee, String firstNameEmployee, String emailEmployee, String mdpEmployee, Set orderses) {
       this.nameEmployee = nameEmployee;
       this.firstNameEmployee = firstNameEmployee;
       this.emailEmployee = emailEmployee;
       this.mdpEmployee = mdpEmployee;
       this.orderses = orderses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdEmployee", unique=true, nullable=false)
    public Long getIdEmployee() {
        return this.idEmployee;
    }
    
    public void setIdEmployee(Long idEmployee) {
        this.idEmployee = idEmployee;
    }

    
    @Column(name="NameEmployee", length=65535)
    public String getNameEmployee() {
        return this.nameEmployee;
    }
    
    public void setNameEmployee(String nameEmployee) {
        this.nameEmployee = nameEmployee;
    }

    
    @Column(name="FirstNameEmployee", length=65535)
    public String getFirstNameEmployee() {
        return this.firstNameEmployee;
    }
    
    public void setFirstNameEmployee(String firstNameEmployee) {
        this.firstNameEmployee = firstNameEmployee;
    }

    
    @Column(name="EmailEmployee", length=65535)
    public String getEmailEmployee() {
        return this.emailEmployee;
    }
    
    public void setEmailEmployee(String emailEmployee) {
        this.emailEmployee = emailEmployee;
    }

    
    @Column(name="MdpEmployee", length=65535)
    public String getMdpEmployee() {
        return this.mdpEmployee;
    }
    
    public void setMdpEmployee(String mdpEmployee) {
        this.mdpEmployee = mdpEmployee;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="employee")
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }




}


