package model;
// Generated 5 mars 2015 20:30:42 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name="employee"
    ,catalog="stockmanager2"
)
public class Employee extends Metier implements java.io.Serializable {


     private Long idEmployee;
     private String nameEmployee;
     private String firstNameEmployee;
     private String emailEmployee;
     private String mdpEmployee;
     private Integer isActive;
     private Set<Invoice> invoices = new HashSet(0);
     private Set<Orders> orderses = new HashSet(0);

    public Employee() {
    }

    public Employee(String nameEmployee, String firstNameEmployee, String emailEmployee, String mdpEmployee, Integer isActive, Set<Invoice> invoices, Set<Orders> orderses) {
       this.nameEmployee = nameEmployee;
       this.firstNameEmployee = firstNameEmployee;
       this.emailEmployee = emailEmployee;
       this.mdpEmployee = mdpEmployee;
       this.isActive = isActive;
       this.invoices = invoices;
       this.orderses = orderses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdEmployee", unique=true, nullable=false)
    public Long getIdEmployee() {
        return this.idEmployee;
    }
    
    public void setIdEmployee(Long idEmployee) {
        this.idEmployee = idEmployee;
    }

    
    @Column(name="NameEmployee", length=65535)
    public String getNameEmployee() {
        return this.nameEmployee;
    }
    
    public void setNameEmployee(String nameEmployee) {
        this.nameEmployee = nameEmployee;
    }

    
    @Column(name="FirstNameEmployee", length=65535)
    public String getFirstNameEmployee() {
        return this.firstNameEmployee;
    }
    
    public void setFirstNameEmployee(String firstNameEmployee) {
        this.firstNameEmployee = firstNameEmployee;
    }

    
    @Column(name="EmailEmployee", length=65535)
    public String getEmailEmployee() {
        return this.emailEmployee;
    }
    
    public void setEmailEmployee(String emailEmployee) {
        this.emailEmployee = emailEmployee;
    }

    
    @Column(name="MdpEmployee", length=65535)
    public String getMdpEmployee() {
        return this.mdpEmployee;
    }
    
    public void setMdpEmployee(String mdpEmployee) {
        this.mdpEmployee = mdpEmployee;
    }

    
    @Column(name="IsActive")
    public Integer getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Integer isActive) {
        this.isActive = isActive;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="employee")
    public Set<Invoice> getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set<Invoice> invoices) {
        this.invoices = invoices;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="employee")
    public Set<Orders> getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set<Orders> orderses) {
        this.orderses = orderses;
    }




}


