package model;
// Generated 2 mars 2015 20:31:41 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Invoice generated by hbm2java
 */
@Entity
@Table(name="invoice"
    ,catalog="stockmanager"
)
public class Invoice  extends Metier   implements java.io.Serializable {


    private InvoiceId id;
    private Product product;
    private Supplier supplier;
    private Long numInvoice;
    private Long quantityInvoice;

    public Invoice() {
    }

	
    public Invoice(InvoiceId id, Product product, Supplier supplier) {
        this.id = id;
        this.product = product;
        this.supplier = supplier;
    }
    public Invoice(InvoiceId id, Product product, Supplier supplier, Long numInvoice, Long quantityInvoice) {
       this.id = id;
       this.product = product;
       this.supplier = supplier;
       this.numInvoice = numInvoice;
       this.quantityInvoice = quantityInvoice;
    }
   
    @EmbeddedId
    @AttributeOverrides( {
    @AttributeOverride(name="idSupplier", column=@Column(name="IdSupplier", nullable=false) ), 
    @AttributeOverride(name="idProduct", column=@Column(name="IdProduct", nullable=false) ) } )
    public InvoiceId getId() {
        return this.id;
    }
    
    public void setId(InvoiceId id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdProduct", nullable=false, insertable=false, updatable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdSupplier", nullable=false, insertable=false, updatable=false)
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }

    
    @Column(name="NumInvoice")
    public Long getNumInvoice() {
        return this.numInvoice;
    }
    
    public void setNumInvoice(Long numInvoice) {
        this.numInvoice = numInvoice;
    }

    
    @Column(name="QuantityInvoice")
    public Long getQuantityInvoice() {
        return this.quantityInvoice;
    }
    
    public void setQuantityInvoice(Long quantityInvoice) {
        this.quantityInvoice = quantityInvoice;
    }




}


