package model;
// Generated 5 mars 2015 13:27:27 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Invoice generated by hbm2java
 */
@Entity
@Table(name="invoice"
    ,catalog="stockmanager"
)
public class Invoice  extends Metier implements java.io.Serializable {


     private long numInvoice;
     private Employee employee;
     private Product product;
     private Supplier supplier;
     private Long quantityInvoice;
     private Date dateInvoice;

    public Invoice() {
    }

	
    public Invoice(long numInvoice, Employee employee, Product product, Supplier supplier) {
        this.numInvoice = numInvoice;
        this.employee = employee;
        this.product = product;
        this.supplier = supplier;
    }
    public Invoice(long numInvoice, Employee employee, Product product, Supplier supplier, Long quantityInvoice, Date dateInvoice) {
       this.numInvoice = numInvoice;
       this.employee = employee;
       this.product = product;
       this.supplier = supplier;
       this.quantityInvoice = quantityInvoice;
       this.dateInvoice = dateInvoice;
    }
   
     @Id 

    
    @Column(name="NumInvoice", unique=true, nullable=false)
    public long getNumInvoice() {
        return this.numInvoice;
    }
    
    public void setNumInvoice(long numInvoice) {
        this.numInvoice = numInvoice;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdEmployee", nullable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdProduct", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdSupplier", nullable=false)
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }

    
    @Column(name="QuantityInvoice")
    public Long getQuantityInvoice() {
        return this.quantityInvoice;
    }
    
    public void setQuantityInvoice(Long quantityInvoice) {
        this.quantityInvoice = quantityInvoice;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DateInvoice", length=19)
    public Date getDateInvoice() {
        return this.dateInvoice;
    }
    
    public void setDateInvoice(Date dateInvoice) {
        this.dateInvoice = dateInvoice;
    }




}


