package model;
// Generated 5 mars 2015 20:30:42 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name="orders"
    ,catalog="stockmanager2"
)
public class Orders extends Metier implements java.io.Serializable {


     private Long numOrder;
     private Customer customer;
     private Employee employee;
     
     private Date dateOrders;
     private  Set<Orderproduct> orderproducts = new HashSet(0);

    public Orders() {
    }

	
    public Orders(Customer customer, Employee employee) {
        this.customer = customer;
        this.employee = employee;
    }
    public Orders(Customer customer, Employee employee, Date dateOrders,  Set<Orderproduct> orderproducts) {
       this.customer = customer;
       this.employee = employee;
       
       this.dateOrders = dateOrders;
       this.orderproducts = orderproducts;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="NumOrder", unique=true, nullable=false)
    public Long getNumOrder() {
        return this.numOrder;
    }
    
    public void setNumOrder(Long numOrder) {
        this.numOrder = numOrder;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="IdCustomer", nullable=false)
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="IdEmployee", nullable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    
    

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DateOrders", length=19)
    public Date getDateOrders() {
        return this.dateOrders;
    }
    
    public void setDateOrders(Date dateOrders) {
        this.dateOrders = dateOrders;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="orders")
    public  Set<Orderproduct> getOrderproducts() {
        return this.orderproducts;
    }
    
    public void setOrderproducts( Set<Orderproduct> orderproducts) {
        this.orderproducts = orderproducts;
    }




}


