package model;
// Generated 5 mars 2015 13:27:27 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name="orders"
    ,catalog="stockmanager"
)
public class Orders extends Metier  implements java.io.Serializable {


     private long numOrder;
     private Customer customer;
     private Employee employee;
     private Product product;
     private Long quantityOrder;
     private Date dateOrders;

    public Orders() {
    }

	
    public Orders(long numOrder, Customer customer, Employee employee, Product product) {
        this.numOrder = numOrder;
        this.customer = customer;
        this.employee = employee;
        this.product = product;
    }
    public Orders(long numOrder, Customer customer, Employee employee, Product product, Long quantityOrder, Date dateOrders) {
       this.numOrder = numOrder;
       this.customer = customer;
       this.employee = employee;
       this.product = product;
       this.quantityOrder = quantityOrder;
       this.dateOrders = dateOrders;
    }
   
     @Id 

    
    @Column(name="NumOrder", unique=true, nullable=false)
    public long getNumOrder() {
        return this.numOrder;
    }
    
    public void setNumOrder(long numOrder) {
        this.numOrder = numOrder;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="IdCustomer", nullable=false)
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdEmployee", nullable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="IdProduct", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="QuantityOrder")
    public Long getQuantityOrder() {
        return this.quantityOrder;
    }
    
    public void setQuantityOrder(Long quantityOrder) {
        this.quantityOrder = quantityOrder;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DateOrders", length=19)
    public Date getDateOrders() {
        return this.dateOrders;
    }
    
    public void setDateOrders(Date dateOrders) {
        this.dateOrders = dateOrders;
    }




}


