package model;
// Generated 3 mars 2015 14:34:36 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name="orders"
    ,catalog="stockmanager"
)
public class Orders extends Metier implements java.io.Serializable {


     private OrdersId id;
     private Customer customer;
     private Employee employee;
     private Product product;
     private Long numOrder;
     private Long quantityOrder;
     private Date dateOrders;

    public Orders() {
    }

	
    public Orders(OrdersId id, Customer customer, Employee employee, Product product) {
        this.id = id;
        this.customer = customer;
        this.employee = employee;
        this.product = product;
    }
    public Orders(OrdersId id, Customer customer, Employee employee, Product product, Long numOrder, Long quantityOrder, Date dateOrders) {
       this.id = id;
       this.customer = customer;
       this.employee = employee;
       this.product = product;
       this.numOrder = numOrder;
       this.quantityOrder = quantityOrder;
       this.dateOrders = dateOrders;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEmployee", column=@Column(name="IdEmployee", nullable=false) ), 
        @AttributeOverride(name="idProduct", column=@Column(name="IdProduct", nullable=false) ), 
        @AttributeOverride(name="idCustomer", column=@Column(name="IdCustomer", nullable=false) ) } )
    public OrdersId getId() {
        return this.id;
    }
    
    public void setId(OrdersId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdCustomer", nullable=false, insertable=false, updatable=false)
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdEmployee", nullable=false, insertable=false, updatable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdProduct", nullable=false, insertable=false, updatable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="NumOrder")
    public Long getNumOrder() {
        return this.numOrder;
    }
    
    public void setNumOrder(Long numOrder) {
        this.numOrder = numOrder;
    }

    
    @Column(name="QuantityOrder")
    public Long getQuantityOrder() {
        return this.quantityOrder;
    }
    
    public void setQuantityOrder(Long quantityOrder) {
        this.quantityOrder = quantityOrder;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DateOrders", length=19)
    public Date getDateOrders() {
        return this.dateOrders;
    }
    
    public void setDateOrders(Date dateOrders) {
        this.dateOrders = dateOrders;
    }




}


