package model;
// Generated 3 mars 2015 09:18:13 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrdersId generated by hbm2java
 */
@Embeddable
public class OrdersId extends Metier implements java.io.Serializable {


     private long idEmployee;
     private long idProduct;
     private long idCustomer;

    public OrdersId() {
    }

    public OrdersId(long idEmployee, long idProduct, long idCustomer) {
       this.idEmployee = idEmployee;
       this.idProduct = idProduct;
       this.idCustomer = idCustomer;
    }
   


    @Column(name="IdEmployee", nullable=false)
    public long getIdEmployee() {
        return this.idEmployee;
    }
    
    public void setIdEmployee(long idEmployee) {
        this.idEmployee = idEmployee;
    }


    @Column(name="IdProduct", nullable=false)
    public long getIdProduct() {
        return this.idProduct;
    }
    
    public void setIdProduct(long idProduct) {
        this.idProduct = idProduct;
    }


    @Column(name="IdCustomer", nullable=false)
    public long getIdCustomer() {
        return this.idCustomer;
    }
    
    public void setIdCustomer(long idCustomer) {
        this.idCustomer = idCustomer;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrdersId) ) return false;
		 OrdersId castOther = ( OrdersId ) other; 
         
		 return (this.getIdEmployee()==castOther.getIdEmployee())
 && (this.getIdProduct()==castOther.getIdProduct())
 && (this.getIdCustomer()==castOther.getIdCustomer());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getIdEmployee();
         result = 37 * result + (int) this.getIdProduct();
         result = 37 * result + (int) this.getIdCustomer();
         return result;
   }   


}


