package model;
// Generated 3 mars 2015 14:34:36 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name="product"
    ,catalog="stockmanager"
)
public class Product extends Metier implements java.io.Serializable {


     private long idProduct;
     private Category category;
     private String nameProduct;
     private String descriptifProduct;
     private Float priceProduct;
     private Integer maxStockProduct;
     private Integer minStockProduct;
     private Integer stockProduct;
     private Set<Orders> orderses = new HashSet(0);
     private Set<Invoice> invoices = new HashSet(0);

    public Product() {
    }

	
    public Product(long idProduct, Category category) {
        this.idProduct = idProduct;
        this.category = category;
    }
    public Product(long idProduct, Category category, String nameProduct, String descriptifProduct, Float priceProduct, Integer maxStockProduct, Integer minStockProduct, Integer stockProduct, Set<Orders> orderses, Set<Invoice> invoices) {
       this.idProduct = idProduct;
       this.category = category;
       this.nameProduct = nameProduct;
       this.descriptifProduct = descriptifProduct;
       this.priceProduct = priceProduct;
       this.maxStockProduct = maxStockProduct;
       this.minStockProduct = minStockProduct;
       this.stockProduct = stockProduct;
       this.orderses = orderses;
       this.invoices = invoices;
    }
   
     @Id 

    
    @Column(name="IdProduct", unique=true, nullable=false)
    public long getIdProduct() {
        return this.idProduct;
    }
    
    public void setIdProduct(long idProduct) {
        this.idProduct = idProduct;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdCategory", nullable=false)
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }

    
    @Column(name="NameProduct", length=65535)
    public String getNameProduct() {
        return this.nameProduct;
    }
    
    public void setNameProduct(String nameProduct) {
        this.nameProduct = nameProduct;
    }

    
    @Column(name="DescriptifProduct", length=65535)
    public String getDescriptifProduct() {
        return this.descriptifProduct;
    }
    
    public void setDescriptifProduct(String descriptifProduct) {
        this.descriptifProduct = descriptifProduct;
    }

    
    @Column(name="PriceProduct", precision=12, scale=0)
    public Float getPriceProduct() {
        return this.priceProduct;
    }
    
    public void setPriceProduct(Float priceProduct) {
        this.priceProduct = priceProduct;
    }

    
    @Column(name="MaxStockProduct")
    public Integer getMaxStockProduct() {
        return this.maxStockProduct;
    }
    
    public void setMaxStockProduct(Integer maxStockProduct) {
        this.maxStockProduct = maxStockProduct;
    }

    
    @Column(name="MinStockProduct")
    public Integer getMinStockProduct() {
        return this.minStockProduct;
    }
    
    public void setMinStockProduct(Integer minStockProduct) {
        this.minStockProduct = minStockProduct;
    }

    
    @Column(name="StockProduct")
    public Integer getStockProduct() {
        return this.stockProduct;
    }
    
    public void setStockProduct(Integer stockProduct) {
        this.stockProduct = stockProduct;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="product")
    public Set<Orders> getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set<Orders> orderses) {
        this.orderses = orderses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="product")
    public Set<Invoice> getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set<Invoice> invoices) {
        this.invoices = invoices;
    }




}


