package model;
// Generated 2 mars 2015 20:31:41 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Supplier generated by hbm2java
 */
@Entity
@Table(name="supplier"
    ,catalog="stockmanager"
)
public class Supplier extends Metier implements java.io.Serializable {


     private Long idSupplier;
     private String nameSupplier;
     private String siretSupplier;
     private String addressSupplier;
     private String villeSupplier;
     private Long cpsupplier;
     private Set invoices = new HashSet(0);

    public Supplier() {
    }

    public Supplier(String nameSupplier, String siretSupplier, String addressSupplier, String villeSupplier, Long cpsupplier, Set invoices) {
       this.nameSupplier = nameSupplier;
       this.siretSupplier = siretSupplier;
       this.addressSupplier = addressSupplier;
       this.villeSupplier = villeSupplier;
       this.cpsupplier = cpsupplier;
       this.invoices = invoices;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdSupplier", unique=true, nullable=false)
    public Long getIdSupplier() {
        return this.idSupplier;
    }
    
    public void setIdSupplier(Long idSupplier) {
        this.idSupplier = idSupplier;
    }

    
    @Column(name="NameSupplier", length=65535)
    public String getNameSupplier() {
        return this.nameSupplier;
    }
    
    public void setNameSupplier(String nameSupplier) {
        this.nameSupplier = nameSupplier;
    }

    
    @Column(name="SiretSupplier", length=65535)
    public String getSiretSupplier() {
        return this.siretSupplier;
    }
    
    public void setSiretSupplier(String siretSupplier) {
        this.siretSupplier = siretSupplier;
    }

    
    @Column(name="AddressSupplier", length=65535)
    public String getAddressSupplier() {
        return this.addressSupplier;
    }
    
    public void setAddressSupplier(String addressSupplier) {
        this.addressSupplier = addressSupplier;
    }

    
    @Column(name="VilleSupplier", length=65535)
    public String getVilleSupplier() {
        return this.villeSupplier;
    }
    
    public void setVilleSupplier(String villeSupplier) {
        this.villeSupplier = villeSupplier;
    }

    
    @Column(name="CPSupplier")
    public Long getCpsupplier() {
        return this.cpsupplier;
    }
    
    public void setCpsupplier(Long cpsupplier) {
        this.cpsupplier = cpsupplier;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="supplier")
    public Set getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set invoices) {
        this.invoices = invoices;
    }




}


