package model;
// Generated 3 mars 2015 14:34:36 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Supplier generated by hbm2java
 */
@Entity
@Table(name="supplier"
    ,catalog="stockmanager"
)
public class Supplier extends Metier implements java.io.Serializable {


     private long idSupplier;
     private String nameSupplier;
     private String siretSupplier;
     private String addressSupplier;
     private String villeSupplier;
     private Long cpsupplier;
     private Set<Invoice> invoices = new HashSet(0);

    public Supplier() {
    }

	
    public Supplier(long idSupplier) {
        this.idSupplier = idSupplier;
    }
    public Supplier(long idSupplier, String nameSupplier, String siretSupplier, String addressSupplier, String villeSupplier, Long cpsupplier, Set<Invoice> invoices) {
       this.idSupplier = idSupplier;
       this.nameSupplier = nameSupplier;
       this.siretSupplier = siretSupplier;
       this.addressSupplier = addressSupplier;
       this.villeSupplier = villeSupplier;
       this.cpsupplier = cpsupplier;
       this.invoices = invoices;
    }
   
     @Id 

    
    @Column(name="IdSupplier", unique=true, nullable=false)
    public long getIdSupplier() {
        return this.idSupplier;
    }
    
    public void setIdSupplier(long idSupplier) {
        this.idSupplier = idSupplier;
    }

    
    @Column(name="NameSupplier", length=65535)
    public String getNameSupplier() {
        return this.nameSupplier;
    }
    
    public void setNameSupplier(String nameSupplier) {
        this.nameSupplier = nameSupplier;
    }

    
    @Column(name="SiretSupplier", length=65535)
    public String getSiretSupplier() {
        return this.siretSupplier;
    }
    
    public void setSiretSupplier(String siretSupplier) {
        this.siretSupplier = siretSupplier;
    }

    
    @Column(name="AddressSupplier", length=65535)
    public String getAddressSupplier() {
        return this.addressSupplier;
    }
    
    public void setAddressSupplier(String addressSupplier) {
        this.addressSupplier = addressSupplier;
    }

    
    @Column(name="VilleSupplier", length=65535)
    public String getVilleSupplier() {
        return this.villeSupplier;
    }
    
    public void setVilleSupplier(String villeSupplier) {
        this.villeSupplier = villeSupplier;
    }

    
    @Column(name="CPSupplier")
    public Long getCpsupplier() {
        return this.cpsupplier;
    }
    
    public void setCpsupplier(Long cpsupplier) {
        this.cpsupplier = cpsupplier;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="supplier")
    public Set<Invoice> getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set<Invoice> invoices) {
        this.invoices = invoices;
    }




}


